# Generated by Django 4.2.16 on 2024-11-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-date_applied']},
        ),
    ]
